# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish TesoHelperV2.csproj -c Release --output release --nologo
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
